name: "🐛 Bug report"
description: Report a reproducible bug or regression
title: "bug: <short description>"
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!

  - type: checkboxes
    id: duplicates
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues and discussions
          required: true

  - type: input
    id: version
    attributes:
      label: Package version
      description: Version of react-iran-maps you're using (from package.json or console)
      placeholder: e.g. 1.2.3

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Provide environment details
      placeholder: |
        Node: v20.x
        React: 18.x
        OS: Windows/macOS/Linux
        Browser: Chrome/Firefox/Safari/Edge (versions)

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide a minimal, reproducible example and steps
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened
    validations:
      required: true

  - type: input
    id: reproduction-link
    attributes:
      label: Minimal reproduction
      description: Link to a minimal repro (CodeSandbox/StackBlitz/GitHub repo)
      placeholder: https://codesandbox.io/s/...

  - type: textarea
    id: logs
    attributes:
      label: Logs/Stack trace
      description: Paste any relevant error output
      render: bash

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
