blank_issues_enabled: false
contact_links:
  - name: Ask a question (GitHub Discussions)
    url: https://github.com/rezasohrabi/react-iran-maps/discussions
    about: If you have a question, please start a discussion here.
