name: "❓ Question"
description: Ask a question about usage or behavior
title: "question: <short description>"
labels: [question]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have you checked the README and existing issues/discussions?

  - type: checkboxes
    id: duplicates
    attributes:
      label: Is there an existing issue or discussion for this?
      options:
        - label: I have searched the existing issues and discussions
          required: true

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: Clearly describe your question
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Relevant code snippet
      description: Paste any relevant code to help explain
      render: tsx

  - type: input
    id: reproduction-link
    attributes:
      label: Minimal reproduction (optional)
      description: Link to CodeSandbox/StackBlitz/GitHub repo if applicable
      placeholder: https://codesandbox.io/s/...

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other information or screenshots that help
